consumer:
  token: 0KWU7AmsuG5KBrjZ50NPNA
  secret: 4PkyfdQVC37iG9qyDcvbSte0EgKpdwPLGJ4LiOeYM
  atoken: 97543182-oZlL7fFptIN8dqJIXkpF5Icwd3jYBEmFkuNABzS0
  asecret: OeLzaa2mnWESeM9MaRhS1Olkb89XhLXCzQ3VZ3bcE
user:
  username: 140_mk_bot
  password: mktwitter2010
